#include "interpretations.h"

vector<string> all_faculties = { "ИКБ", "ИТУ", "ИПТИП", "ИИТ", "ИИИ", "ИТХТ", "ИРИ" };

vector <vector <string>> TermSubjects{
        {"Eng", "History", "IT", "LineAlg", "MathAn", "PE", "Physics", "ProgLang", "Russian", "VPD"},
        {"DiscMath", "Economics", "Eng", "History", "LineAlg", "MathAn", "PE", "Physics", "ProgLang"},
        {"AI", "DiffEq", "ElTech", "Eng", "Law", "LineAlg", "MathAn", "MathLog", "PE", "SocPsycho"},
        {"BigData", "BusModel", "ElTech", "Eng", "OS", "OrgEVM", "PE", "Phyl", "TeorVer", "UgrAndUya"},
        {"ASModel", "BioSys", "BusModel", "Crypto", "Networks", "TeorDB", "UgrAndUya"},
        {"BZD", "BioSys", "Crypto", "DBSafety", "PAMethods", "TechSafeMethods", "VSSafety"},
        {"DBSafety", "PAMethods", "PaySafety", "TeorRel"},
        {"ISAdmin", "InfProtection", "MakeAS", "MarkIB", "PAMethods"},
        {"ASSafety", "DiagCZ", "MakeAS", "ManageIB", "ProtectGos"},
};

map<string, string> subjectsInterpretations{
    pair <string, string>{"LineAlg", "Линейная алгебра"},
    pair <string, string>{"MathAn", "Математический анализ"},
    pair <string, string>{"Physics", "Физика"},
    pair <string, string>{"History", "История"},
    pair <string, string>{"IT", "Информатика"},
    pair <string, string>{"Russian", "Русский язык"},
    pair <string, string>{"VPD", "ВПД"},
    pair <string, string>{"PE", "Физ-ра"},
    pair <string, string>{"Eng", "Иностранный язык"},
    pair <string, string>{"ProgLang", "Языки программирования"},
    pair <string, string>{"Economics", "Экономическая культура"},
    pair <string, string>{"DiscMath", "Дискретная математика"},
    pair <string, string>{"DiffEq", "Дифференциальные уравнения"},
    pair <string, string>{"MathLog", "Математическая логика"},
    pair <string, string>{"Law", "Правоведение"},
    pair <string, string>{"ElTech", "Электротехника"},
    pair <string, string>{"AI", "ИИ"},
    pair <string, string>{"SocPsycho", "Социальная психология"},
    pair <string, string>{"Phyl", "Философия"},
    pair <string, string>{"Electronics", "Электроника"},
    pair <string, string>{"TeorVer", "Теория вероятностей"},
    pair <string, string>{"OS", "ОС"},
    pair <string, string>{"BigData", "Большие данные"},
    pair <string, string>{"OrgEVM", "Организация ЭВМ"},
    pair <string, string>{"UgrAndUya", "Угрозы и уязвимости"},
    pair <string, string>{"BusModel", "Моделирование бизнес-процессов"},
    pair <string, string>{"Crypto", "Криптография"},
    pair <string, string>{"Networks", "Сети"},
    pair <string, string>{"TeorDB", "Теория баз данных"},
    pair <string, string>{"BioSys", "Биометрические системы"},
    pair <string, string>{"ASModel", "Моделирование АС"},
    pair <string, string>{"BZD", "БЖД"},
    pair <string, string>{"PAMethods", "Программно-аппаратные средства защиты"},
    pair <string, string>{"VSSafety", "Безопасность ВС"},
    pair <string, string>{"DBSafety", "Безопасность баз данных"},
    pair <string, string>{"TechSafeMethods", "Технические средства защиты"},
    pair <string, string>{"TeorRel", "Основы теории надёжности"},
    pair <string, string>{"PaySafety", "Безопасность платёжных систем"},
    pair <string, string>{"InfProtection", "Защита информации"},
    pair <string, string>{"ISAdmin", "Администрирование ИС"},
    pair <string, string>{"MarkIB", "Оценка ИБ"},
    pair <string, string>{"MakeAS", "Разработка АС"},
    pair <string, string>{"ManageIB", "Управление ИБ"},
    pair <string, string>{"DiagCZ", "Диагностика систем защиты"},
    pair <string, string>{"ProtectGos", "Защита Гос. ИС"},
    pair <string, string>{"ASSafety", "Безопасность АС"},
};